// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgQRRZmaWLGLWiDoUswTMPosz9IfuhF8o',
    appId: '1:783628828891:web:85e7b683208378282f4cfe',
    messagingSenderId: '783628828891',
    projectId: 'provincias-af807',
    authDomain: 'provincias-af807.firebaseapp.com',
    storageBucket: 'provincias-af807.firebasestorage.app',
    measurementId: 'G-0HKVHZVB8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBp42euA_mLz6-y7kxG7n7ZVXtHNbmLdQ',
    appId: '1:783628828891:android:4de7bbad890a5d0a2f4cfe',
    messagingSenderId: '783628828891',
    projectId: 'provincias-af807',
    storageBucket: 'provincias-af807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNMUhjda45aQOOaueMasBk8S6v0a40Ak',
    appId: '1:783628828891:ios:a889fbec851c1f1d2f4cfe',
    messagingSenderId: '783628828891',
    projectId: 'provincias-af807',
    storageBucket: 'provincias-af807.firebasestorage.app',
    iosBundleId: 'com.example.flutterProvincias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlNMUhjda45aQOOaueMasBk8S6v0a40Ak',
    appId: '1:783628828891:ios:a889fbec851c1f1d2f4cfe',
    messagingSenderId: '783628828891',
    projectId: 'provincias-af807',
    storageBucket: 'provincias-af807.firebasestorage.app',
    iosBundleId: 'com.example.flutterProvincias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgQRRZmaWLGLWiDoUswTMPosz9IfuhF8o',
    appId: '1:783628828891:web:a6076743d07299bf2f4cfe',
    messagingSenderId: '783628828891',
    projectId: 'provincias-af807',
    authDomain: 'provincias-af807.firebaseapp.com',
    storageBucket: 'provincias-af807.firebasestorage.app',
    measurementId: 'G-4Y8D3SFGN6',
  );

}